run:
  concurrency: 4
  deadline: 1m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  dupl:
    threshold: 80
  errcheck:
    check-type-assertions: false
    check-blank: false
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 10
  gofmt:
    simplify: true
  golint:
    min-confidence: 0.8
  govet:
    check-shadowing: false
    use-installed-packages: false
  lll:
    line-length: 120
  maligned:
    suggest-new: true
  misspell:
    locale: US
    ignore-words:
      - cheque
  nakedret:
    max-func-lines: 30
  unused:
    check-exported: false
  unparam:
    algo: cha
    check-exported: false

linters:
  enable:
    - deadcode
    - errcheck
    - gas
    - gochecknoinits
    - gocritic
    - gocyclo
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
  enable-all: false
  disable:
    - depguard
    - dupl
    - gochecknoglobals
    - goconst
    - interfacer
    - maligned
    - prealloc
    - scopelint
    - unparam
  disable-all: false

issues:
  exclude-use-default: false
  max-per-linter: 1024
  max-same: 1024
