language: go

go:
  - "1.12"
  - "1.13"
  - "1.14"

branches:
  only:
  - master
  - v1
  - v2

before_install:
  - go get golang.org/x/lint/golint
  - go get golang.org/x/tools/cmd/cover

script:
  - ./checks.sh
  - go test -v -race -coverprofile coverage.txt -covermode atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

