language: go

go:
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"

branches:
  only:
  - master
  - v1
  - v2

before_install:
  - go get -v golang.org/x/lint/golint

script:
  - ./checks.sh
  - go test ./...